name: Maven Build

on:
  pull_request:
    branches:
      - dev
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Clona il repository nella VM
      - name: Checkout code
        uses: actions/checkout@v2

      # Configura la JDK nella VM 
      - name: Set up JDK 20
        uses: actions/setup-java@v2
        with:
          java-version: '20'

      - name: Build with Maven
        run: mvn clean install -DskipTests=true

      - name: Run tests with Maven
        run: mvn test --fail-fast --batch-mode --show-version --errors --quiet --file pom.xml