name: Java CI with Maven

permissions:
  contents: write

on:
  pull_request:
    branches:
      - main
      - dev
  push:
    branches:
      - f/*

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: 17
        cache: 'maven'

    - name: Default value Build Badge 
      run: |
        sed -i '/Build Status/c\Build Status: ![Build Status](https://img.shields.io/badge/Build-Failed-red)' README.md
        
    - name: Defualt value Validation Badge
      run: |
        sed -i '/Validation Status/c\Validation Status: ![Validation Status](https://img.shields.io/badge/Validation-Failed-red)' README.md

    - name: Analisi statica con Maven
      id: maven_analysis
      run: mvn clean validate --file roman-number/pom.xml

    - name: Build with Maven
      id: maven_build
      run: mvn clean install --file roman-number/pom.xml

    - name: Build Badge
      if: always() && steps.maven_build.outcome == 'success'
      run: |
        sed -i '/Build-Failed-red/c\Build Status: ![Build Status](https://img.shields.io/badge/Build-Success-green)' README.md

    - name: Validation Badge
      if: always() && steps.maven_analysis.outcome == 'success'
      run: |
        sed -i '/Validation-Failed-red/c\Validation Status: ![Validation Status](https://img.shields.io/badge/Validation-Success-green)' README.md

    - name: Spostare il report di copertura
      run: mv roman-number/target/site/jacoco/jacoco.xml .github/badge/

    - name: Committa e pusha il badge aggiornato
      if: always()
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add .github/badge/jacoco.xml
        git add README.md
        git commit -m "Aggiornamento badge di copertura JaCoCo" || echo "Nessuna modifica da commettere"
        git push