name: Java CI with Maven

on:
  pull_request:
    branches: [dev, main]
  push:
    branches: [dev_local_test]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 20
        uses: actions/setup-java@v2
        with:
          java-version: '20'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn -B install --fail-fast --batch-mode --show-version --file pom.xml